### ISSUE TITLE
Build hangs, buildsome not servicing fshook calls and prints "Process completed, but still has likely-leaked children connected to FS hooks"

### ISSUE THREAD

**Issue by sinelaw** [ElastiLotem/buildsome#64]
Buildsome prints repeatedly:

> Process completed, but still has likely-leaked children connected to FS hooks

And build is hung. There are processes stuck waiting for response from buildsome in fshook.

**Comment by ElastiLotem** [comment]
This is a bug in the build rules, I think:

Some build command is forking children and exits.

Buildsome cannot service these children because it does not know when the last request will arrive, if ever, so it relies on the command's exit as the signal that no more requests will arrive.

Without this signal, it cannot work correctly.

So I think the command ought to be fixed to only exit once it is truly completed.
